<main>
    <h1>Register</h1>
    <form method="post" action="phtml/logic/register.php">
        <label for="first_name">First Name</label>
        <input type="text" name="first_name">
        <br>
        <label for="last_name">Last Name</label>
        <input type="text" name="last_name">
        <br>
        <label for="email">Email</label>
        <input type="email" name="email">
        <br>
        <label for="password">Password</label>
        <input type="password" name="password">
        <br>
        <input type="submit" value="Submit"/>
    </form>
</main>